position = "bottom"
height = 42

[[center]]
type = "focused"
show_icon = true
show_title = true
icon_size = 32
truncate = "end"

[[end]]
type = "volume"
format = "{icon} {percentage}%"
max_volume = 100
truncate = "middle"

[end.icons]
volume_high = "🔊"
volume_medium = "🔉"
volume_low = "🔈"
muted = "🔇"

[[end]]
type = "clock"
format = "        %H:%M\n%d/%m/%Y"

[[end]]
type = "network_manager"
icon_size = 32

[[end]]
type = "upower"
format = "{percentage}%"

[[end.thresholds]]
warning = 20
critical = 5
